//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asyncimageupload
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        [Key]
        public int userid { get; set; }

        [Required(ErrorMessage = "please provide username", AllowEmptyStrings = false)]
        public string username { get; set; }
        
        [Required(ErrorMessage = "please provise password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "password must be 8 characters long")]
        public string password { get; set; }
        
        [Compare("password", ErrorMessage = "confirm password does not match with password field")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string confirm_password { get; set; }
        
        [Required(ErrorMessage = "please enter full name", AllowEmptyStrings = false)]
        public string fullname { get; set; }
        
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$", ErrorMessage = "please provide valid emailid")]
        public string emailid { get; set; }

        
        public byte[] image { get; set; }
    }
}
